name: Deploy to Server

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup SSH key
              run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
                  chmod 600 deploy_key.pem

            - name: Deploy to server
              run: |
                  ssh -i deploy_key.pem -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
                    echo "Pulling latest image..."
                    docker pull registry.digitalocean.com/o3o/my-app:latest

                    echo "Restarting container..."
                    docker stop my-app || true
                    docker rm my-app || true
                    docker run -d --name my-app registry.digitalocean.com/o3o/my-app:latest
                  EOF

            - name: Cleanup SSH key
              run: rm -f deploy_key.pem
